vich_uploader:
    db_driver: orm

    mappings:
        immobiliers:
            uri_prefix: /images/immobiliers
            upload_destination: '%kernel.project_dir%/public/images/immobiliers'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\OrignameNamer
